CREATE TABLE `measurements`
( 
`STN` INT NOT NULL , 
`TIMESTAMP` TIMESTAMP , 
`TEMP` FLOAT ,
`DEWP` FLOAT , 
`STP` FLOAT , 
`SLP` FLOAT , 
`VISIB` FLOAT , 
`WDSP` FLOAT ,
`PRCP` FLOAT ,
`SNDP` FLOAT ,
`FRSHTT` VARCHAR(6) ,
`CLDC` FLOAT ,
`WNDDIR` INT
) 
ENGINE = InnoDB;

ALTER TABLE measurements
  ADD CONSTRAINT measurements_stations_stn_fk
FOREIGN KEY (STN) REFERENCES stations (stn);